export const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const label=status=>({excluded:'ACTIVE EXCLUSION', 'possible-match':'POSSIBLE MATCH — REVIEW REQUIRED',clear:'NO MATCH'})[status]||'NOT SCREENED';
function csvCell(value) {let text=String(value??'');if(/^[\s]*[=+\-@]/.test(text)||/^[\t\r\n]/.test(text))text="'"+text;return '"'+text.replaceAll('"','""')+'"';}
export function vendorCsv(vendors) {
  const header=['Vendor','UEI','CAGE','Archived at','Screened at','Result','Match type','Confidence','Source date','Source file','Snapshot SHA-256','Reviewed at','Evidence'];
  return [header,...vendors.map(v=>{const s=v.watch?.latest||{};return[v.legalName,v.uei,v.cage,v.archivedAt,s.screenedAt,label(s.status),s.matchType,s.confidence,s.source?.sourceDate,s.source?.sourceFile,s.source?.sha256,s.acknowledgedAt,JSON.stringify(s.matches||[])];})].map(row=>row.map(csvCell).join(',')).join('\r\n');
}
export function screeningReport(vendor,history) {
  const esc=escapeHtml;
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>ExcluSignal screening report</title><style>body{font:16px system-ui;max-width:900px;margin:2rem auto;padding:1rem;overflow-wrap:anywhere}article{border-top:1px solid #aaa;padding:1rem 0}pre{white-space:pre-wrap} @media print{article{break-inside:avoid}body{margin:0}}</style></head><body><h1>ExcluSignal — Screening report</h1><p>Use your browser’s Print → Save as PDF.</p><h2>${esc(vendor.legalName||'Unnamed vendor')}</h2><p>UEI: ${esc(vendor.uei||'Not available')} · CAGE: ${esc(vendor.cage||'Not available')}</p><p>${vendor.archivedAt?'Archived '+esc(vendor.archivedAt):'Active watchlist'}</p>${history.length?history.map(s=>`<article><h2>${esc(label(s.status))}</h2><dl>${Object.entries({'Screened at':s.screenedAt,'Match type':s.matchType,Confidence:s.confidence,'SAM source date':s.source?.sourceDate,'SAM filename':s.source?.sourceFile,'Snapshot hash':s.source?.sha256,'Snapshot fetched at':s.source?.fetchedAt,'Stale snapshot':s.source?.stale===true?'Yes':s.source?.stale===false?'No':null,'Reviewed at':s.acknowledgedAt,'Review required':s.alert&&!s.acknowledgedAt?'Yes':'No',Reason:s.reason}).map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v??'Not available')}</dd>`).join('')}</dl><h3>Source matches</h3><pre>${esc(JSON.stringify(s.matches||[],null,2))}</pre></article>`).join(''):'<p>No screening evidence available.</p>'}<footer>ExcluSignal is screening and decision support, not a legal eligibility determination. Name-only matches require human review. No match means only that no matching active record was found in the referenced snapshot. This report contains retained screening history, not a guarantee of current status.</footer></body></html>`;
}
