export const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const label=status=>({excluded:'ACTIVE EXCLUSION', 'possible-match':'POSSIBLE MATCH — REVIEW REQUIRED',clear:'NO MATCH'})[status]||'NOT SCREENED';
function csvCell(value) {let text=String(value??'');if(/^[\s]*[=+\-@]/.test(text)||/^[\t\r\n]/.test(text))text="'"+text;return '"'+text.replaceAll('"','""')+'"';}
export function vendorCsv(vendors) {
  const header=['Vendor','UEI','CAGE','Archived at','Screened at','Result','Match type','Confidence','Source date','Source file','Snapshot SHA-256','Acknowledged at (automatic for non-alerts)','Evidence'];
  return [header,...vendors.map(v=>{const s=v.watch?.latest||{};return[v.legalName,v.uei,v.cage,v.archivedAt,s.screenedAt,label(s.status),s.matchType,s.confidence,s.source?.sourceDate,s.source?.sourceFile,s.source?.sha256,s.acknowledgedAt,JSON.stringify(s.matches||[])];})].map(row=>row.map(csvCell).join(',')).join('\r\n');
}
export function screeningReport(vendor,history,{generatedAt=new Date()}={}) {
  const esc=escapeHtml;
  const displayDate=value=>{
    if(!value)return 'Not available';
    const date=new Date(value);
    return Number.isNaN(date.getTime())?esc(value):`<time datetime="${esc(value)}">${esc(new Intl.DateTimeFormat('en-US',{dateStyle:'medium',timeStyle:'short',timeZone:'UTC'}).format(date))} UTC</time><small class="rawTime">${esc(value)}</small>`;
  };
  const fields=values=>Object.entries(values).map(([key,value])=>`<div><dt>${esc(key)}</dt><dd>${esc(value??'Not available')}</dd></div>`).join('');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>ExcluSignal screening report</title><style>
  *{box-sizing:border-box}body{font:15px/1.5 system-ui,sans-serif;color:#14213d;background:#f4f7fb;margin:0;padding:32px 16px}main{max-width:900px;margin:auto;background:white;border:1px solid #dce3ee;padding:32px;border-radius:12px}header{border-bottom:3px solid #14213d;padding-bottom:18px;display:flex;justify-content:space-between;gap:20px;flex-wrap:wrap}h1{font-size:22px;margin:0}h2{font-size:21px;margin:0 0 8px}h3{font-size:16px}p{margin:8px 0}small,.hint{color:#536078}.identity{padding:22px 0}.eyebrow{font-size:11px;letter-spacing:.1em;text-transform:uppercase;font-weight:750}.result{border-left:5px solid #3157d5;padding:14px;background:#f1f5ff;margin:12px 0}.result.excluded{border-color:#a32319;background:#fff3f1}.result.possible-match{border-color:#9a630a;background:#fff8e9}article{border-top:1px solid #dce3ee;padding:18px 0}dl{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin:14px 0}dt{font-size:11px;color:#536078;font-weight:700}dd{margin:3px 0 0;overflow-wrap:anywhere}.rawTime{display:block;font-size:10px}footer{border-top:1px solid #dce3ee;padding-top:18px;font-size:11px;color:#43516a}.match{border:1px solid #dce3ee;padding:14px;margin:12px 0;border-radius:8px}.match dl{font-size:12px}pre{white-space:pre-wrap;overflow-wrap:anywhere}@media(max-width:600px){main{padding:18px}dl{grid-template-columns:1fr}header{display:block}}@media print{@page{size:auto;margin:15mm}body{padding:0;background:white;font-size:11px}main{border:0;padding:0;max-width:none}header{padding-bottom:10px}h1,h2{font-size:17px}.identity{padding:12px 0}.printHint{display:none}article{padding:10px 0}.result{padding:10px;margin:8px 0}dl{gap:8px;grid-template-columns:1fr 1fr}.result,.match,dl>div{break-inside:avoid}h2,h3{break-after:avoid}footer{font-size:9px}.rawTime{font-size:8px}}
  </style></head><body><main><header><div><h1>ExcluSignal</h1><p class="eyebrow">Screening evidence report</p></div><div><span class="eyebrow">Generated</span><div>${displayDate(generatedAt.toISOString())}</div></div></header><section class="identity"><h2>${esc(vendor.legalName||'Unnamed vendor')}</h2><dl>${fields({UEI:vendor.uei||null,CAGE:vendor.cage||null,'Watchlist state':vendor.archivedAt?'Archived':'Active','Archived at':vendor.archivedAt||null})}</dl></section><p class="printHint hint">Use your browser’s Print → Save as PDF. This report includes retained screening history.</p>${history.length?history.map(s=>`<article><div class="result ${['excluded','possible-match','clear'].includes(s.status)?s.status:''}"><p class="eyebrow">Screening result</p><h2>${esc(label(s.status))}</h2><p>${esc(s.reason||'')}</p></div><dl><div><dt>Screening timestamp</dt><dd>${displayDate(s.screenedAt)}</dd></div>${fields({'Match type':s.matchType,...((s.matches||[]).length&&s.confidence?{'Match confidence':s.confidence}:{}),'SAM source date':s.source?.sourceDate,'SAM source filename':s.source?.sourceFile,'Snapshot SHA-256':s.source?.sha256,'Snapshot fetched at':s.source?.fetchedAt,'Stale snapshot':s.source?.stale===true?'Yes — refresh due':s.source?.stale===false?'No':null,'Review status':s.alert?(s.acknowledgedAt?'Alert marked reviewed':'Alert awaiting review'):'No alert; automatic acknowledgement'})}<div><dt>Acknowledged at</dt><dd>${displayDate(s.acknowledgedAt)}</dd></div></dl><h3>Exclusion evidence</h3>${(s.matches||[]).length?s.matches.map((match,index)=>`<section class="match"><strong>Matching record ${index+1}</strong><dl>${fields(Object.fromEntries(Object.entries(match).map(([key,value])=>[key,typeof value==='object'?JSON.stringify(value):value])))}</dl></section>`).join(''):'<p>No matching exclusion records in the referenced snapshot.</p>'}</article>`).join(''):'<p>No screening evidence available.</p>'}<footer>ExcluSignal is screening and decision support, not a legal eligibility determination. Name-only matches require human review. No match means only that no matching active record was found in the referenced snapshot. This report contains retained screening history, not a guarantee of current status.</footer></main></body></html>`;
}
